import { CounterProvider } from "./context/countercontext";
import "./globals.css";
import { Dancing_Script } from "next/font/google";

const dancingscript = Dancing_Script({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Create Next App",
    template: `%s | Next App`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  analytics,
  team,
  children,
}: {
  analytics: React.ReactNode;
  team: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={intr.className}>
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  );
}
