import { CounterProvider } from './context/countercontext';
import './globals.css';
import { Inter } from 'next/font/google';

const intr = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  analytics,
  team,
  children,
}: {
  analytics: React.ReactNode;
  team: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={intr.className}>
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  );
}
